export const teamData = [
  {
    icon: "fa-solid fa-user",
    data1: "Malakai Feki",
    data2: "Prop",
    data3: "31",
    data4: "188 cm",
    data5: "115 kg",
    data6: "140",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Kai Patel",
    data2: "Prop",
    data3: "24",
    data4: "183 cm",
    data5: "120 kg",
    data6: "20",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Koa Williams",
    data2: "Hooker",
    data3: "25",
    data4: "176 cm",
    data5: "110 kg",
    data6: "15",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Tama Kauri",
    data2: "Hooker",
    data3: "24",
    data4: "181 cm",
    data5: "118 kg",
    data6: "34",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Michael Brown",
    data2: "Lock",
    data3: "28",
    data4: "200 cm",
    data5: "125 kg",
    data6: "89",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Jordan Smith",
    data2: "Lock",
    data3: "32",
    data4: "196 cm",
    data5: "122 kg",
    data6: "164",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Xavier Taylor",
    data2: "Flanker",
    data3: "29",
    data4: "185 cm",
    data5: "112 kg",
    data6: "101",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Devon Robinson",
    data2: "Flanker",
    data3: "23",
    data4: "190 cm",
    data5: "109 kg",
    data6: "78",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Tane Ma’afu",
    data2: "Scrum-half",
    data3: "29",
    data4: "172 cm",
    data5: "85 kg",
    data6: "123",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Sam White",
    data2: "Scrum-half",
    data3: "30",
    data4: "169 cm",
    data5: "78 kg",
    data6: "142",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Andre Wilson",
    data2: "Fly-half",
    data3: "21",
    data4: "180 cm",
    data5: "87 kg",
    data6: "34",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Scott Pryer",
    data2: "Fly-half",
    data3: "26",
    data4: "176 cm",
    data5: "83 kg",
    data6: "87",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Sione Takauha",
    data2: "Centre",
    data3: "24",
    data4: "183 cm",
    data5: "95 kg",
    data6: "50",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Kevin Nguyen",
    data2: "Centre",
    data3: "25",
    data4: "187 cm",
    data5: "100 kg",
    data6: "37",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Jose Martinez",
    data2: "Wing",
    data3: "18",
    data4: "178 cm",
    data5: "92 kg",
    data6: "5",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Darnel Hyatt",
    data2: "Wing",
    data3: "23",
    data4: "181 cm",
    data5: "94 kg",
    data6: "18",
  },
  {
    icon: "fa-solid fa-user",
    data1: "John Smith",
    data2: "Fullback",
    data3: "24",
    data4: "175 cm",
    data5: "90 kg",
    data6: "65",
  },
  {
    icon: "fa-solid fa-user",
    data1: "Rob Dane",
    data2: "Fullback",
    data3: "23",
    data4: "190 cm",
    data5: "89 kg",
    data6: "68",
  },
];
